### ISSUE TITLE
Running Plugin Issue

### ISSUE THREAD

**Issue by kw5sk8d** [nextgis/qgis_qtiles#107]
When trying to run plug in in QGIS 2.18.14 with Qtiles 1.5.2.1 results in python failure

Im hoping for a few ideas to address this. 

V/R,

Derek

TypeError: QgsCollapsibleGroupBox.setSettings(QgsSettings): argument 1 has unexpected type 'QSettings' 
Traceback (most recent call last):
  File "C:/Users/derek/.qgis2/python/plugins\qtiles\qtiles.py", line 95, in run
    d = qtilesdialog.QTilesDialog(self.iface)
  File "C:/Users/derek/.qgis2/python/plugins\qtiles\qtilesdialog.py", line 68, in __init__
    self.grpParameters.setSettings(self.settings)
TypeError: QgsCollapsibleGroupBox.setSettings(QgsSettings): argument 1 has unexpected type 'QSettings'

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.14 Las Palmas, c11191e133 

Python Path:
C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins\processing
C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python
C:/Users/derek/.qgis2/python
C:/Users/derek/.qgis2/python/plugins
C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\bin\python27.zip
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\DLLs
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\plat-win
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\lib-tk
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\bin
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/derek/.qgis2//python
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\boundlessconnect\extlibs
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\boundlessconnect\extlibs\future-0.16.0-py2.7.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\boundlessconnect\extlibs\qgiscommons-2.0.5-py2.7.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\extlibs

####
Traceback (most recent call last):
			  File "C:/Users/derek/.qgis2/python/plugins\qtiles\qtiles.py", line 95, in run
			    d = qtilesdialog.QTilesDialog(self.iface)
			  File "C:/Users/derek/.qgis2/python/plugins\qtiles\qtilesdialog.py", line 68, in __init__
			    self.grpParameters.setSettings(self.settings)
			TypeError: QgsCollapsibleGroupBox.setSettings(QgsSettings): argument 1 has unexpected type 'QSettings'

**Comment by dezhin** [comment]
It should work in the current version. Let us know if it doesn't.
