### ISSUE TITLE
Not working in 3.28

### ISSUE THREAD

**Issue by alhirzel** [nextgis/qgis_qtiles#118]
Does not work on QGIS 3.28, and gives the following error visible in the console:

```
TypeError: setDotsPerMeterX(self, a0: int): argument 1 has unexpected type 'float'

Traceback (most recent call last):
 File "/home/alhirzel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qtiles/tilingthread.py", line 146, in run
 self.writeOverviewFile()
 File "/home/alhirzel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qtiles/tilingthread.py", line 218, in writeOverviewFile
 image.setDotsPerMeterX(dpm)
TypeError: setDotsPerMeterX(self, a0: int): argument 1 has unexpected type 'float'

Python version: 3.10.8 (main, Nov 1 2022, 14:18:21) [GCC 12.2.0]

QGIS version: 3.28.1-Firenze Firenze, exported

Python Path:

/usr/share/qgis/python/home/alhirzel/.local/share/QGIS/QGIS3/profiles/default/python/home/alhirzel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/usr/share/qgis/python/plugins/usr/lib/python310.zip/usr/lib/python3.10/usr/lib/python3.10/lib-dynload/home/alhirzel/.local/lib/python3.10/site-packages/usr/lib/python3.10/site-packages/home/alhirzel/.local/share/QGIS/QGIS3/profiles/default/python/home/alhirzel/redacted_path
```

**Comment by simgislab** [comment]
Hello, can't reproduce it here yet

![изображение](https://user-images.githubusercontent.com/172806/203539646-9fb469fe-b0af-46f3-be97-82709d34b4cf.png)

**Comment by agiudiceandrea** [comment]
@simgislab the error only occurs if the Python version used by QGIS is >= 3.10.

**Comment by friederschueler** [comment]
I can reproduce this error with the following setup

`QGIS-Version | 3.28.1-Firenze | QGIS-Codezweig | Release 3.28
-- | -- | -- | --
Qt-Version | 5.15.7
Python-Version | 3.10.8
Kompiliert mit GDAL/OGR | 3.6.0 | Läuft mit GDAL/OGR | 3.6.1
Kompiliert mit PROJ | 9.1.0.%3.%4 | Läuft mit PROJ | 9.1.1
EPSG-Registraturdatenbankversion | v10.076 (2022-08-31)
Kompiliert mit GEOS | 3.11.0-CAPI-1.17.0 | Läuft mit GEOS | 3.11.1-CAPI-1.17.1
SQLite-Version | 3.40.0
PDAL-Version | 2.4.3
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.2.0

Error message is: TypeError: setDotsPerMeterX(self, a0: int): argument 1 has unexpected type 'float'
             
             
             Traceback (most recent call last):
              File "/home/frieder/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qtiles/tilingthread.py", line 169, in run
              self.render(t)
              File "/home/frieder/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qtiles/tilingthread.py", line 303, in render
              image.setDotsPerMeterX(dpm)
             TypeError: setDotsPerMeterX(self, a0: int): argument 1 has unexpected type 'float'`

**Comment by kauevestena** [comment]
> @simgislab the error only occurs if the Python version used by QGIS is >= 3.10.

Here I'm having the same problem...

Installed the plugin today...

**Comment by simgislab** [comment]
thanks everyone for participation
new version with this fix is up online
