### ISSUE TITLE
export as file does not work

### ISSUE THREAD

**Issue by StacktraceException** [nextgis/qgis_qtiles#122]
the only time i got it work when i  specified the filename to be with a .zip extension. But this is a big problem, because all the tiles are still individual files. A singel file  is needed so that qgis can import it  as one layer instead of thousands of separate layers. 

are there any image formats that it supports as export? i tried a tif but it doesn't work  then.

please fix the problem.

**Comment by dezhin** [comment]
The purpose of this plugin is to make tiles. For exporting as an image you can use QGIS built-in image export for example.
