### ISSUE TITLE
QTILES plugin not working

### ISSUE THREAD

**Issue by mibmib** [nextgis/qgis_qtiles#127]
I'm writing about the QTILES plugin for QGIS.
It has worked brilliantly before, but for some reason, when I make the files now, they don't work anymore.
The tiles get created and seem to be ok, but when I try to view the tile layer, they don't show up at all.

Has something changed in the plugin, or in QGIS?

**Comment by ivanbarsukov** [comment]
Hello, Matthew! Thank you for creating this issue. Can you please provide more information about your environment (OS, QGIS and plugin version) and QTiles export settings?

**Comment by mibmib** [comment]
It turns out the problem was with my Azure hosting environment, not with QTILES.  I don't know what was wrong with Azure. I think you can close this.

**Comment by ivanbarsukov** [comment]
Okay. Feel free to reopen the issue if needed!
