### ISSUE TITLE
MBTiles support

### ISSUE THREAD

**Issue by simgislab** [nextgis/qgis_qtiles#3]
Support MBTiles format for export

**Comment by simgislab** [comment]
It is implemented.

Guide needs to be updated.

**Comment by agilebotanist** [comment]
Could you tell me how to run MBTiles export? Which options to choose?

Thanks, Andrey

**Comment by agilebotanist** [comment]
Ok, I think I found that.

One would need to choose File export and choose .mbtiles instead of .zip

Is it correct?

**Comment by simgislab** [comment]
what else could it be, really)
