### ISSUE TITLE
Label not appearing in exported tiles

### ISSUE THREAD

**Issue by olivierdalang** [nextgis/qgis_qtiles#32]
Hi !

Under QGIS 2.6, the labels are completely missing from the tiles.
It worked well under QGIS 2.0.

I guess it's related to some changes to the rendering pipeline in QGIS ?

Thanks for the great plugin !

Olivier

**Comment by simgislab** [comment]
Hi, just checked, on our build (http://nextgis.ru/nextgis-qgis, based on 2.8.4) everything works well with labels.

Can you update, check again and let me know? 

![](http://m-d.me/img/ss/20150903-24r-435kb.jpg)
