### ISSUE TITLE
Not all layers rendering in QGIS 2.8.1

### ISSUE THREAD

**Issue by trolleway** [nextgis/qgis_qtiles#35]
Windows 7
QGIS 2.8 original & NextGIS

Layers in QGIS
![scr1](https://cloud.githubusercontent.com/assets/4630662/6679469/ec6116d4-cc82-11e4-8c6f-9d3e36e17095.png)

Not all of them appears in rendered tiles
![screenshot_2015-03-16-16-08-43](https://cloud.githubusercontent.com/assets/4630662/6679485/0cf26308-cc83-11e4-899f-4cfccfb7bec2.png)

In Ubuntu all layers is rendering

**Comment by trolleway** [comment]
Project and test data: https://drive.google.com/file/d/0B7MbofRLwMpCd2FkN3pucm5fOWs/view?usp=sharing

**Comment by alisovenko** [comment]
Please try the new version of the plugin
