### ISSUE TITLE
Adding a checkbox to make QTiles ignore projects background color

### ISSUE THREAD

**Issue by simgislab** [nextgis/qgis_qtiles#7]
Hi, a nice feature would be to have a checkbox in ui to make QTiles ignore the projects background color (and therefore results in rendering PNGs with transparency) This feature could be easily implemnted by adding a oneliner to tilingthread.py

if <checbox in ui to ignore backgroundcolor> is true:
if int(QT_VERSION_STR2) >= 8:
self.color = QColor(myRed, myGreen, myBlue, 0)
else:
self.color = qRgb(myRed, myGreen, myBlue, 0)
else:
if int(QT_VERSION_STR2) >= 8:
self.color = QColor(myRed, myGreen, myBlue)
else:
self.color = qRgb(myRed, myGreen, myBlue)

May be (did not check) it also works to step over self.image.fill(self.color) if checkbox is set.

Originally at: http://hub.qgis.org/issues/9682

**Comment by Crossmotion** [comment]
This problem is also mentioned in #9 and #4 all tree are marked as duplicate... so i am curious, what is the original post and why is it still not fixed?

**Comment by simgislab** [comment]
Is this still a problem (needed functionality)?

**Comment by Crossmotion** [comment]
I think so. Not sure if I am experiencing the same problems as above. But when I export a layer as PNG and import it in my openlayers project, the tiles have a transparent white background even if I set the transparancy to 100. 
![transparancy](https://cloud.githubusercontent.com/assets/13520878/21887218/54c90624-d8bf-11e6-8c96-bcc7a58240fe.jpg)

**Comment by simgislab** [comment]
@alisovenko please have a look when time permits

**Comment by Crossmotion** [comment]
@alisovenko do you know when you can look into this?

**Comment by simgislab** [comment]
After discussion, to be short, we don't know. There two ways to speed it up:
- pull-requests
- development sponsorship

**Comment by Crossmotion** [comment]
@simgislab can you give me a quote for option 2?

**Comment by fnorf** [comment]
@Crossmotion , this is just a documentation problem. The background transparency values are used like this:

Background transparency 255 means the background color will be used in full opacity.
Background transparency 0 means the background color will be used in full transparency.

Your value of 100 will be quite transparent but not totally, like you noticed.

**Comment by xiaohe** [comment]
Background transparency set to 0 fixed my problem.
