### ISSUE TITLE
Please add support for UTFGrid

### ISSUE THREAD

**Issue by kannes** [nextgis/qgis_qtiles#84]
UTFGrid is a way of providing attributes of the original data.
The format is documented at https://github.com/mapbox/utfgrid-spec
A leaflet implementation is available at https://github.com/danzel/Leaflet.utfgrid

UTFGrid is used in Tilemill, letting users select attributes to be included and displayed on mouse hover in the resulting map.

Adding UTFGrid support would allow QTiles to not only export static images but enhance them with original data values and more.

**Comment by dezhin** [comment]
As of 2023, UTFGrid seems to be dead. If you need vector data on a client side MVT is a better choice. But it's not within the scope of this plugin.
